version: "3.9"
services:
  chatapp:
    build: .
    ports:
      - "4567:4567"
    environment:
      DB_URL: "jdbc:postgresql://db:5432/chatapp"
      DB_USER: "postgres"
      DB_PASSWORD: "example"
      PORT: "4567"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
